### ISSUE TITLE
Unable to build example android app

### ISSUE THREAD

**Issue by MrBuggySan** [cjam/react-native-spotify-remote#47]
Hey @cjam ,
I'm trying to check out the android project but it is not compiling. 

I'm getting the following error after `npx react-native run-android`

```
> Task :react-native-spotify-remote:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings
28 actionable tasks: 2 executed, 26 up-to-date
/react-native-spotify-remote/android/src/main/java/com/reactlibrary/RNSpotifyRemoteAppModule.java:17: error: package com.spotify.andro
id.appremote.api does not exist
import com.spotify.android.appremote.api.ConnectionParams;
                                        ^
/react-native-spotify-remote/android/src/main/java/com/reactlibrary/RNSpotifyRemoteAppModule.java:18: error: package com.spotify.andro
id.appremote.api does not exist
import com.spotify.android.appremote.api.Connector;
                                        ^
/react-native-spotify-remote/android/src/main/java/com/reactlibrary/RNSpotifyRemoteAppModule.java:19: error: package com.spotify.andro
id.appremote.api does not exist
import com.spotify.android.appremote.api.SpotifyAppRemote;
                                        ^
/react-native-spotify-remote/android/src/main/java/com/reactlibrary/RNSpotifyRemoteAppModule.java:23: error: package com.spotify.protocol.client does not exist
import com.spotify.protocol.client.CallResult;

```

So I went to /android and tried to build from there and got:
```
> Configure project :
Adding external libraries []

FAILURE: Build failed with an exception.

* Where:
Build file '/react-native-spotify-remote/android/build.gradle' line: 84

* What went wrong:
A problem occurred evaluating root project 'android'.
> Project with path ':react-native-events' could not be found in root project 'android'.
```
but inside /node_modules/ it is clear that `react-native-events/android` is there.

Any further steps I should try?

**Comment by cjam** [comment]
Hey @MrBuggySan

From the root project. Can you try and do the following.  I’m using yarn but you can do the equivalent with npm

`yarn submodules`

`cd ./example`

`yarn` to install the packages

`cd ../`

`yarn example` 

which will run the packager and the example server

I usually open up android studio and build the example app from there.

**Comment by MrBuggySan** [comment]
Thanks @cjam 
Now I'm getting something like this after following your steps:
 
   ```
 Body:
    {"type":"InternalError","errors":[],"message":"Metro has encountered an error: While trying to resolve module `react-native-spotify-remote` from file `/mobileTech/react-native-spotify-remote/example/AppContext.tsx`, the package `/mobileTech/react-native-spotify-remote/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/mobileTech/react-native-spotify-remote/dist/index.js`. Indeed, none of these files exist:\n\n  * /mobileTech/react-native-spotify-remote/dist/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)\n  * /mobileTech/react-native-spotify-remote/dist/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)"}
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:276)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:35)
        at com.facebook.react.devsupport.BundleDownloader$2.onChunkComplete(BundleDownloader.java:201)
        at com.facebook.react.devsupport.MultipartStreamReader.emitChunk(MultipartStreamReader.java:70)
        at com.facebook.react.devsupport.MultipartStreamReader.readAllParts(MultipartStreamReader.java:152)
        at com.facebook.react.devsupport.BundleDownloader.processMultipartResponse(BundleDownloader.java:185)
        at com.facebook.react.devsupport.BundleDownloader.access$100(BundleDownloader.java:35)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:151)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Looking at my directory, there wasn't a dist/ that was built? is there another config missed here?

**Comment by cjam** [comment]
Ah I missed a step sorry. 

Try and run `yarn build`

**Comment by cjam** [comment]
Sorry about the poor documentation. I’ll probably take some these steps and put them into the Contributing.md

**Comment by MrBuggySan** [comment]
It works now, thank you @cjam !
